### Create new user
POST http://localhost:3001/createUser
Content-Type: application/json

# create student user
{
    "role": "student",
    "username": "alex5",
    "first_name": "Alex",
    "last_name": "Smith",
    "email": "alex.smith5@stu.mtec.edu",
    "telephone": "5555555555",
    "address": "55 North 5000 East",
    "password": "password5"
}

# create admin user
# {
#     "role": "admin",
#     "username": "michael5",
#     "first_name": "Michael",
#     "last_name": "Miner",
#     "email": "michael.miner5@mtec.edu",
#     "telephone": "5555555555",
#     "address": "555 South 505 West",
#     "password": "password5"
# }


### Get Student Token
POST http://localhost:3001/studentLogin
Content-Type: application/json

# student user has access to student home page
{
    "username": "eva4",
    "password": "password4"
}


### Get Admin Token
POST http://localhost:3001/adminLogin
Content-Type: application/json

# admin user has access to admin routes including /getStudents
{
    "username": "bella3",
    "password": "password3"
}


### Get courses
GET http://localhost:3001/courses
Authorization: Bearer 


### Get student home page
GET http://localhost:3001/studentDashboard
Authorization: Bearer 


### Get admin home page
GET http://localhost:3001/adminDashboard
Authorization: Bearer 
